apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mealie-web-route
  namespace: mealie
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mealie.shubhrajitpallob.dev`)
      kind: Rule
      services:
        - name: mealie
          port: 9000
  tls:
    secretName: shubhrajit-pallob-tls # This is the "Padlock" you got from cert-manager!
