apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-clusterissuer
spec:
  acme:
    # The ACME server address for Let's Encrypt production
    server: https://acme-v02.api.letsencrypt.org/directory
    # Your email address for renewal reminders
    email: shubhrajitpallob228@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            email: shubhrajitpallob228@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
